### ISSUE TITLE
getting started with CSS

### ISSUE THREAD

**Issue by loosenut** [Thomas101/wmail-user-scripts#17]
I noticed that when using the Inspector tool in Wavebox, I can only get object#browser-plugin for Google Inbox (and other apps).  I'm sure I could dig deeper if I opened the window in my browser, but my question is, how can I determine the CSS selector for any object in that window?  I want to hide the Trash and Checkmark at the top of each Bundle.

**Comment by Thomas101** [comment]
It sounds like you might have run into the Wavebox window inspector rather than the tab inspector. If you try right clicking on some of the Google Inbox UI and then picking inspect this will bring up the inspector for Google Inbox rather than Wavebox. You should be able to use some normal selectors to get down to the element from there.

The custom css styles get applied to the inbox tab directly rather than via the main window etc

**Comment by loosenut** [comment]
Thank you!
